
  services:

    mysql:
      image: mysql:8.4
      container_name: mysql
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ports:
        - "3306:3306"
      volumes:
        - mysql-data:/var/lib/mysql
        - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      networks:
        - library-network
      healthcheck:
        test:
          - CMD
          - mysqladmin
          - ping
          - -h
          - localhost
        interval: 10s
        timeout: 5s
        retries: 10


    eureka-server:
      build: ./eureka-server
      container_name: eureka-server
      ports:
        - "8761:8761"
      depends_on:
        mysql:
          condition: service_healthy
      networks:
        - library-network


    api-gateway:
      build: ./api-gateway
      container_name: api-gateway
      environment:
        JAVA_TOOL_OPTIONS: "-Deureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/ -Dapp.jwt.secret=${JWT_SECRET} -Dapp.jwt.expiration=${JWT_EXPIRATION}"
      ports:
        - "8080:8080"
      depends_on:
        eureka-server:
          condition: service_started
      networks:
        - library-network


    auth-service:
      build: ./auth-service
      container_name: auth-service
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book_db
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        JWT_SECRET: ${JWT_SECRET}
        JWT_EXPIRATION: ${JWT_EXPIRATION}
        JAVA_TOOL_OPTIONS: "-Deureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/"
      ports:
        - "8081:8080"
      depends_on:
        mysql:
          condition: service_healthy
        eureka-server:
          condition: service_started
      networks:
        - library-network


    book-service:
      build: ./book-service
      container_name: book-service
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book_db
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        JAVA_TOOL_OPTIONS: "-Deureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/"
      ports:
        - "8082:8080"
      depends_on:
        mysql:
          condition: service_healthy
        eureka-server:
          condition: service_started
      networks:
        - library-network


    cart-service:
      build: ./cart-service
      container_name: cart-service
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book_db
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        JAVA_TOOL_OPTIONS: "-Deureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/"
      ports:
        - "8083:8080"
      depends_on:
        mysql:
          condition: service_healthy
        eureka-server:
          condition: service_started
      networks:
        - library-network


    order-service:
      build: ./order-service
      container_name: order-service
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book_db
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        JAVA_TOOL_OPTIONS: "-Deureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/"
      ports:
        - "8085:8080"
      depends_on:
        mysql:
          condition: service_healthy
        eureka-server:
          condition: service_started
      networks:
        - library-network


    inventory-service:
      build: ./inventory-service
      container_name: inventory-service
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book_db
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        JAVA_TOOL_OPTIONS: "-Deureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/"
      ports:
        - "8086:8080"
      depends_on:
        mysql:
          condition: service_healthy
        eureka-server:
          condition: service_started
      networks:
        - library-network


    review-service:
      build: ./review-service
      container_name: review-service
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book_db
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        JAVA_TOOL_OPTIONS: "-Deureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/"
      ports:
        - "8087:8080"
      depends_on:
        mysql:
          condition: service_healthy
        eureka-server:
          condition: service_started
      networks:
        - library-network


    payment-service:
      build: ./payment-service
      container_name: payment-service
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book_db
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        JAVA_TOOL_OPTIONS: "-Deureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/"
      ports:
        - "8088:8080"
      depends_on:
        mysql:
          condition: service_healthy
        eureka-server:
          condition: service_started
      networks:
        - library-network


    user-service:
      build: ./user-service
      container_name: user-service
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book_db
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        JAVA_TOOL_OPTIONS: "-Deureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/"
      ports:
        - "8089:8080"
      depends_on:
        mysql:
          condition: service_healthy
        eureka-server:
          condition: service_started
      networks:
        - library-network


    notification-service:
      build: ./notification-service
      container_name: notification-service
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book_db
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        JAVA_TOOL_OPTIONS: "-Deureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/"
      ports:
        - "8090:8080"
      depends_on:
        mysql:
          condition: service_healthy
        eureka-server:
          condition: service_started
      networks:
        - library-network


    recommendation-service:
      build: ./recommendation-service
      container_name: recommendation-service
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book_db
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        JAVA_TOOL_OPTIONS: "-Deureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/"
      ports:
        - "8091:8080"
      depends_on:
        mysql:
          condition: service_healthy
        eureka-server:
          condition: service_started
      networks:
        - library-network


  volumes:
    mysql-data:


  networks:
    library-network:
      driver: bridge

