spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:

            - id: auth-public
              uri: http://localhost:8081
              predicates:
                - Path=/auth/login,/auth/register

            - id: book-service
              uri: http://localhost:8082
              predicates:
                - Path=/books/**
              filters:
                - jwtFilter

            - id: cart-service
              uri: http://localhost:8083
              predicates:
                - Path=/cart/**
              filters:
                - jwtFilter

            - id: order-service
              uri: http://localhost:8085
              predicates:
                - Path=/orders/**
              filters:
                - jwtFilter

            - id: inventory-service
              uri: http://localhost:8086
              predicates:
                - Path=/inventory/**
              filters:
                - jwtFilter

            - id: review-service
              uri: http://localhost:8087
              predicates:
                - Path=/reviews/**
              filters:
                - jwtFilter

            - id: payment-service
              uri: http://localhost:8088
              predicates:
                - Path=/payments/**
              filters:
                - jwtFilter

            - id: user-service
              uri: http://localhost:8089
              predicates:
                - Path=/users/**
              filters:
                - jwtFilter

            - id: notification-service
              uri: http://localhost:8090
              predicates:
                - Path=/notifications/**
              filters:
                - jwtFilter

            - id: recommendation-service
              uri: http://localhost:8091
              predicates:
                - Path=/recommendations/**
              filters:
                - jwtFilter

server:
  port: 8099

app:
  jwt:
    secret: bXlzZWNyZXRrZXlteXNlY3JldGtleW15c2VjcmV0a2V5MTIzNDU2