spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://mysql:3306/inventory_db
    username: root
    password:
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  server:
    port: 8086

  eureka:
    client:
      service-url:
        defaultZone: http://mysql:8761/eureka

  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
      path: /swagger-ui.html

  management:
    endpoints:
      web:
        exposure:
          include: health
    endpoint:
      health:
        show-details: always

  logging:
    file:
      name: logs/inventory-service.log
    level:
      root: INFO
      com.library.inventoryservice: DEBUG